### PR TITLE
fix parameters values issues; fix IOs width values issue

### PR DESCRIPTION
**Pull request by codingUniv**

### CODE REVIEW

**Comment by jjts** [comment]
This issue was causing the parameter to be replaced with the default value but want the literal, right?

**Comment by codingUniv** [comment]
- Parameters: we are interested in the value. But it was not correctly replaced.
  Example: instead of getting 32 as value of BE_DATA_W, we got BE_32 
  The suggested solution fixes the issue.
- IOs width: we are also interested in the literal. But it was not correctly replaced.
  Example:  USE_CTRL+ADDR_W-4.0_W 
  The suggested solution fixes the problem.

**Comment by jjts** [comment]
do you mean 32 is the typical value in the table?

**Comment by codingUniv** [comment]
Yes

**Pull request merged**
