### PR TITLE
Upgrade `board_client.py` to replace Makefile handling and `trap` commands.

### PR DESCRIPTION
**Pull request by arturum1**
**Note**: This PR upgrades the `board_client.py` and `board_server.py` to the version `0.2`. Only the  `board_client.py` has changes, but the communication protocol is the same. The version of the `board_server.py` was only upgraded to prevent version mismatch errors with the new `board_client.py`. The new `board_server.py` should be installed on the machines that share FPGA boards.

The FPGA checks in https://github.com/IObundle/iob-soc/pull/546 have not yet passed, as the new `board_server.py` has not been installed in those machines. Once installed, the FPGA checks should pass.

**Changelog**
- Re-add verilator `--timing` flag as it is required for opencryptolinux. This reverts commit 56eabd0.
- Remove diff with `test.expected` file and instead compare with `Test passed!` string.
  - This change is a partial revert of commit 3a676f5.
  - The commit 3a676f5 had re-added the diff with the `test.expected` file without implementing the same change in the `fpga/Makefile` and `pc-emul/Makefile`. It also did not provide an explanation for this change.
  - By reverting that commit, we use the `Test passed!` string that was originally implemented in the commit b9d2ea4.
- Modified `board_client.py` to handle the: fpga programming; simulator; pc-emulation; and console processes.
  - It now handles interrupt signals and closes the respective processes.
  - It keeps running while the board is grabbed.
  - It has a new timeout feature. If the processes that it handles exceed the timeout, it stops them.
  - It also runs in simulation and pc-emul, it controls the simulator and console processes. In these modes of operation, it does not connect to the `board_server.py`.
  - It has a list of active processes and kills them if it receives an interrupt, timeout, or if they finish.
  - Upgrade `board_client.py` version from `0.1` to `0.2`. This change is due to significant modifications to this program in this PR. Note that there are no changes related to the communication protocol with the board server. Therefore, this version is compatible with the current server implementation (`board_server.py` version 0.1) even though it would give a version mismatch error.
- Upgrade `board_server.py` version from `0.1` to `0.2`. There are no changes in the `board_server.py` contents, however this change is needed to match the new `board_client.py` version.
 - Add `-t` flag to some ssh connections that may require interrupting the remote process or sending signals to it. The `-t` flag forces pseudo-terminal allocation, forwarding every signal received to the remote process.

### CODE REVIEW

**Comment by P-Miranda** [comment]
Controlling the fpga program and console processes via board_client is a good improvement, since for FPGA we need to share the single board connection.
However, using `board_client.py` for the pc-emul and simulation cases does not seem justified.
With this addition we get (pros):
- timeout for pc-emul and simulation processes, along with console process timeout
- uniform command call for pc-emul, simulation and FPGA

however, on the oposing side (cons):
- multiple pc-emulations or simulations do not share resources, therefore a central management is artificial
- increased `board_client.py` complexity
- the `console` script is already a common call between simulation and FPGA (pc-emul does not use console). The `board_client.py` functionality be absorved by console (or vice-versa), since `console` and `board_client` are used in the same cases, only a single script is required

## Other remarks
- the argument complexity for `board_client.py` justifies using the standard [argparse](https://docs.python.org/3/library/argparse.html) library instead of an ad-hoc argument parsing logic
- organize the `board_client.py` script code to have have the runtime code in a delimited section instead of having function definitions between the runtime code:
```Python
# board_client.py
# constants
CONST1 = value1
CONST2 = value2

# functions
def func1():
  return f1
def func2():
  return f2

# runtime code - only runs if ./board_client.py is executed, 
# does not run on import board_client
if __name__ == "__main__":
  # runtime code here
```
- `proc_wait(sim_proc, remaining_duration)` fails outside of simultation case [line](https://github.com/IObundle/iob-lib/blob/7d5cf245cfc015743f0032f951943ad0eb8a5478/scripts/board_client.py#L250)
  - outside simulation case we have:
```Python
simulator_run_command = None  # if there is no f "-s" argument
sim_proc = None # no simulation process if there is no simulation

# this always runs at the end of board_client
proc_wait(sim_proc = None, remaining_duration)

# Function to wait for a process to finish
# If the process times out, kill all other processes
# if proc = None, the try - except does not catch the 
# AttributeError: 'NoneType' object has no attribute 'wait' exception and will fail
def proc_wait(proc, timeout):
    try:
        proc.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        print(f"{iob_colors.FAIL}Board grab duration expired!{iob_colors.ENDC}")
        kill_processes()  
```

**Comment by jjts** [comment]
My 2 cents:

> Multiple pc-emulations or simulations do not share resources. Therefore central management is artificial

This way Console is handled consistently. Multiple simulations may share CPUs and memories; preventing others from using the resources makes sense, but we may add a non-exclusive flag allowing others to run their emulations or simulations.

 > increased board_client.py complexity

But the complexity of several Makefiles has reduced. Finding Python maintainers is easier than Makefile ones.

> the console script is already a common call between pc-emul, simulation and FPGA. The board_client.py functionality will be absorved by console (or vice-versa), since console and board_client are used in the same cases, only a single script is required

I made a similar comment privately to Artur. The suggestion was to import console from board_client.py

>the argument complexity for board_client.py justifies using the standard argparse library instead of an ad-hoc argument parsing logic
>organize the board_client.py script code to have have the runtime code in a delimited section instead of having function definitions between the runtime code:


I agree with both of the above comments

**Comment by arturum1** [comment]
I have implemented the suggested changes in commit 16962d7:
- Fixed `proc_wait(sim_proc, remaining_duration)` outside of simulation
- Added [argparse](https://docs.python.org/3/library/argparse.html)
- Refactored code

In relation to the advantages, besides the ones mentioned in https://github.com/IObundle/iob-lib/pull/486#issuecomment-1514542937, the main motivation for these changes of the `board_client.py` was to remove the `trap` commands and release targets from the Makefiles, as they were causing some problems, like leaving the `console.py` running after timeout.

**Comment by jjts** [comment]
I will merge -- console is still a command line program, but it is well-proven, and the implications of making it a Python module are not worth the trouble. 

On the plus side, one can continue using it standalone.

**Pull request merged**
